### ISSUE TITLE
KeyError: 'block_height' on getting block headers

### ISSUE THREAD

**Issue by nkuba** [summa-tx/bitcoin-spv#17]
I tried to run:
```sh
pipenv run python scripts/merkle.py 79cbf066c8fd6f5503ba5ca11499a205c32280337d5d595aa05f958f2badb624
```
It failed with a following error stack trace:
```sh
Traceback (most recent call last):
  File "scripts/merkle.py", line 227, in <module>
    main(tx_id, num_headers)
  File "scripts/merkle.py", line 219, in main
    asyncio.get_event_loop().run_until_complete(do_it_all(tx_id, num_headers))
  File "/Users/jakub/.pyenv/versions/3.6.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "scripts/merkle.py", line 180, in do_it_all
    (tx_json, t) = await get_tx(tx_id)
  File "scripts/merkle.py", line 106, in get_tx
    latest_blockheight = await get_latest_blockheight()
  File "scripts/merkle.py", line 88, in get_latest_blockheight
    return block_dict['block_height']
KeyError: 'block_height'
```

`block_height` should be replaced with `height`.

Sample `block_dic` received inside `get_latest_blockheight()` function:
```
{'hex': '00008020becf7e0d9f907582aa71142bf1d4eb6d94c1d3778246290000000000000000000f5490fb4c1a11327d806844f76b817410ade60f6d82c47533ae249e2aee9c7bd470e65c45fb2917b138e8c8', 'height': 577391}
```

**Comment by prestwich** [comment]
Both this and #16 were the result of the (hardcoded) server bumping protocol version. I just pushed a commit addressing this, so the script should work on master now
